vvaltchev/tilck

- .travis.yml
- build_toolchain
- kernel/debug_utils.c
- kernel/include/arch/generic_x86/x86_utils.h
- kernel/include/common_defs.h
- kernel/include/config.h
- kernel/main.c
- kernel/process.c
- kernel/term.c
- run_qemu_nographic
- system_tests/run_system_test
- unittests/CMakeLists.txt
This change makes exOS to write on the serial port COM1 everything that it shown on the screen and introduces an actual basic system test written in python that checks (for now) that no kernel panic or reboot occurred. In addition, the new system test has been integrated to run in Travis as well.
> Introducing system testing

- bootloader/boot.asm
- kernel/CMakeLists.txt
- kernel/arch/i386/irq.c
- kernel/arch/i386/kernelAsm.asm
- kernel/arch/i386/process32.c
- kernel/debug_utils.c
- kernel/include/arch/generic_x86/x86_utils.h
- kernel/include/arch/i386/arch_utils.h
- kernel/include/common_defs.h
- kernel/include/irq.h
- kernel/include/process.h
- kernel/include/tasklet.h
- kernel/interrupts.c
- kernel/kb.c
- kernel/main.c
- kernel/misc.c
- kernel/process.c
- kernel/sched.c
- kernel/tasklet.c
- kernel/test_stuff/testrunners.c
- kernel/timer.c
- other_scripts/resolve_bt
- unittests/generic_mocks.c
- unittests/tests_main.cpp
- usermode_init/init.c
This huge change solves many problems related with handling of nested interrupts and significantly improves the robustness of the kernel by adding many new constraints. In addition, the kernel panic has been improved a lot.
> Bugfixing2

- scripts/templates/qemu/run_efi_qemu32
- scripts/templates/qemu/run_efi_qemu64
- scripts/templates/qemu/run_multiboot_qemu
- scripts/templates/qemu/run_qemu
> [scripts] Check for presence of KVM with `lsmod | grep kvm`

- docs/contributing.md
Really small fix, i feel like this is nicer instead of displaying the raw link
> [readme] nicer link on contribting.md

- .azure-pipelines.yml
Added the two folders to excluded paths
> [azure] small fix to ci 

- scripts/cmake-configurator/cmake-configurator.yml
- scripts/cmake-configurator/parser/cmake_parser.py
- scripts/cmake-configurator/parser/cmake_row.py
- scripts/cmake-configurator/parser/cmake_variable.py
- scripts/cmake-configurator/parser/test_cmakeparser.py
- scripts/cmake-configurator/parser/test_cmakerow.py
- scripts/cmake-configurator/parser/test_cmakevariable.py
Updated #106 with better software design, and also made sure that CI/CD works
> [cmake-configurator] First steps: introduce the parser

- docs/building.md
- scripts/tc/pkgs/README
- scripts/tc/pkgs/gcc_tc
- scripts/tc/pkgs/install_pkgs
Used find and replace to change them, since i don't think toolchian is ever an actual word
> [readme] replaced toolchian with toolchain

- other/coverage_build.yml
> [ci-fix] Removing rendundant download of codecov

- scripts/configurator/parser/cmake_parser.py
- scripts/configurator/parser/cmake_row.py
- scripts/configurator/parser/cmake_var.py
- scripts/configurator/parser/test_cmakeparser.py
- scripts/configurator/parser/test_cmakerow.py
> [configurator] extracted rendundant functionalities into cmake_var

- scripts/configurator/parser/cmake_parser.py
- scripts/configurator/parser/cmake_row.py
- scripts/configurator/parser/cmake_var.py
Behaviour is the same as before, but code is more explicit
> [configurator] Added more type checking

- scripts/configurator/configurator.yml
- scripts/configurator/parser/test_cmakeparser.py
> Configurator: add a unit test for the write_file() func + fixes in the CI

- scripts/dev/count_lines_of_code
While looking around I added some type hinting. Makes the code a bit more explicit in my opinion.
> [scripts] added type hinting to count_lines_of_code

- other/containers/arch-base/Dockerfile
- other/containers/debian-base/Dockerfile
- other/containers/fedora-base/Dockerfile
- other/containers/opensuse-base/Dockerfile
Pretty self explanatory, all test pass (assuming CI has changes proposed in #136)
> [ci] added dockerfiles for containers in toolchain_build

- other/containers/tilck-ci-build/Dockerfile
> [docker] Update the tilck-ci-build to v2

- common/string_util.c
- include/tilck/common/string_util.h
- tests/unit/string_util_test.cpp
100% coverage as required. Maybe variable naming should be improved, but i think that' s about it.
https://app.codecov.io/gh/michelececcacci/tilck/blob/addtest/common/string_util.c
> [gtest] added tests for string_util (#145)

- include/tilck/kernel/test/tracing.h
- modules/tracing/ptype_buffer.c
- other/cmake/wrapped_syms.cmake
- tests/unit/mocked_funcs.h
- tests/unit/mocking.cpp
- tests/unit/mocking.h
- tests/unit/tracerTest.cpp
Closes https://github.com/vvaltchev/tilck/issues/147
> [gtests] Add tests for save_param_buffer() and dump_param_buffer()

- kernel/arch/i386/start.S
- kernel/arch/x86_64/linker_script.ld
- kernel/arch/x86_64/start.S
This is the first milestone of porting Tilck to x86-64.
> [64-bit] Make Tilck to enter long mode

- tests/system/test_misc.c
Hello! This fixes #176
Is the tag right? There's also [devshell] but didn't seem relevant.
> [system_tests] Increase getrusage test attempt limit

- NOTICE
Hi @vvaltchev
Please review，thanks！
> [legal] Add in NOTICE an item for fdt_helper.c/h

- include/tilck/kernel/arch/riscv/arch_utils.h
- include/tilck/kernel/hal.h
- kernel/arch/riscv/kernel_yield.S
- kernel/arch/riscv/process_riscv.c
- kernel/user.c
Hi @vvaltchev 
Please review, thanks:-)
> [riscv64] Implement process management on riscv

- include/tilck/kernel/arch/riscv/arch_utils.h
- kernel/arch/riscv/process_riscv.c
> [riscv] Access regs_t members using portable inline function

- kernel/arch/riscv/timer.c
Hi @vvaltchev 
Sorry to upload so many PR at once, but basically they are little things like timer, rtc..., which are relatively simple and do not affect others, so I chose to upload them at once;
The last PR is the syscall part, which changes slightly more than the previous PR. After this PR merged the riscv64 porting work is basically complete.
> [riscv] Implement system timer

- modules/rtc/riscv/fdt_rtc.c
- modules/rtc/riscv/fdt_rtc.h
- modules/rtc/riscv/goldfish.c
> [riscv] Implement the goldfish rtc driver

- modules/serial/riscv/fdt_serial.c
- modules/serial/riscv/fdt_serial.h
- modules/serial/riscv/ns16550.c
The fdt serial is built on top of original serial framework.
> [riscv] Implement fdt based serial driver

- kernel/arch/riscv/misc.S
- kernel/arch/riscv/misc.c
- modules/sysfs/sysfs_int.h
1. include bogomips support, reboot(), poweroff()
2. increase SYSFS_ENTRY_SIZE from 64 to 128  (Note: because of 64bit)
> [riscv] Implement misc

- kernel/kmalloc/kmalloc.c
- tests/unit/kmalloc_test.cpp
This commit fixes the corner case in per_heap_kmalloc_unsafe() where `multi_step_alloc` and `do_actual_alloc` are both true and one of the calls to internal_kmalloc() failed because h->valloc_and_map() failed.
@aenrbes
> [kmalloc] Fix corner case in per_heap_kmalloc_unsafe()

- include/tilck/kernel/signal.h
- include/tilck/kernel/sys_types.h
- include/tilck/kernel/syscalls.h
- kernel/arch/riscv64/arch_syscalls.c
- kernel/fs/fs_syscalls.c
- kernel/interrupts.c
- kernel/mm/process_mm.c
- kernel/poll.c
- kernel/select.c
- kernel/syscalls.c
Hi @vvaltchev 
This is milestone for the riscv64 port, now it can successfully complete all system tests.
> [riscv64] Minimal support for riscv64 system calls
