vvaltchev/tilck

- Makefile
- bootloader/boot_stage1.asm
- bootloader/realModeStrings.inc
- run_qemu_hda
- win_run_bochs.bat
- win_run_bochs_hd.bat
Improving the stage1 of the bootloader and making possible to boot using also a hard drive, after fixing a nasty problem in the build system. (exos.img was less than 2880 sectors, due to a previous unlucky change in the main Makefile.)
The exos.img file has been tested on a real PC by booting using an usbstick (seen as drive 0), as well.
> Working on bootloader

- kernel/arch/i386/idt.c
- kernel/arch/i386/process32.c
- kernel/include/arch/i386/process_int.h
- kernel/include/list.h
- kernel/kcond.c
- kernel/kmutex.c
- kernel/process.c
- kernel/sched.c
- unittests/list_test.cpp
This change makes list.h more aligned with the coding style of exOS and removes any similarities with the list.h in the linux kernel. Only the general idea of an intrusive doubly-linked list remains, clearly.
> Updating the implementation of list.h

- scripts/adv/gen_other_builds
- scripts/adv/test_all_other_builds
- scripts/bash_includes/script_utils
- scripts/bash_includes/tc/cmake_download
- scripts/bash_includes/tc/gcc_tc
- scripts/bash_includes/tc/install_pkgs
- scripts/build_scripts/create_empty_img_if_necessary
- scripts/build_toolchain
- scripts/cmake_run
- scripts/dev/virtualbox_create_vmdk_loop0
- scripts/templates/build_fatpart
- scripts/templates/build_test_fatpart
- scripts/templates/generate_coverage_report
- scripts/templates/qemu/debug_run_qemu
- scripts/templates/qemu/run_efi_nokvm_qemu32
- scripts/templates/qemu/run_efi_nokvm_qemu64
- scripts/templates/qemu/run_efi_qemu32
- scripts/templates/qemu/run_efi_qemu64
- scripts/templates/qemu/run_multiboot_qemu
- scripts/templates/qemu/run_nokvm_qemu
- scripts/templates/qemu/run_qemu
Use `#!/usr/bin/env bash`, instead of `#!/bin/bash` as bash is not in the `/bin/` dir in all *nix systems.
> [scripts]: Make the bash scripts a bit more portable

- kernel/fs/vfs/vfs.c
- kernel/syscalls.c
The corner case was simply not handled due to an oversight.
In addition to that, this patch fixes vfs_utimens_impl() in vfs.c to
handle correctly the case where the path is non-existent.
> [syscalls] Support NULL u_times param in sys_utimes()

- other/cmake/config_fatpart
- other/cmake/extra_apps.cmake
- other/toolchain_builds.yml
- scripts/bash_includes/tc/lua
- scripts/templates/build_fatpart
Hey!
I got interested in this project and I would like to make a small contribution.
I am making this PR to add Lua interpreter support. I have added all the necessary scripts in `scripts/bash_includes/tc/lua` and also I have added `add_lua` routine in `templates/build_fatpart` .
As you know Lua is a tiny interpreter and it is a cool nice feature to have in the toolchain. Having Lua in the toolchain would allow anyone to build cool new features with Lua scripting language. (Most of the hobby operating systems I have seen has a Lua port).
None of the kernel functions are modified as a part of this PR.
I have tried my best to maintain the same coding standards as yours, so that there will be a uniformity.
Please review the PR, I am happy to make any changes you request.
Regards,
Prasanna
> Added Lua support

- scripts/templates/qemu/run_efi_qemu32
- scripts/templates/qemu/run_efi_qemu64
- scripts/templates/qemu/run_multiboot_qemu
- scripts/templates/qemu/run_qemu
I am using Windows Subsystem for Linux (version 2), and several scripts in `build/` could not detect that to warn me that I cannot use KVM. The reason is that in my case the output of `uname -a` contains `microsoft` (completely lowercase) rather than `Microsoft`:
```
$ uname -a
Linux DESKTOP-78BKHO2 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
I have changed the scripts so that they do a case-independent search for "microsoft", and now they prevent me from running KVM scripts.
> [scripts] Fix WSL detection via uname

- scripts/tc/pkgs/install_pkgs
Add support toolchain-package build  for Arch-compatible Artix distribution.
> [toolchain] add ArtixLinux support

- modules/acpi/osl_misc.c
For details, see the end of the issue #99
> Typo in showing PM1x registers

- README.md
- docs/building.md
- docs/coverage.md
- docs/testing.md
Even if parallel builds of Tilck work perfectly, on machines with a
scarse amount of RAM (e.g. < 4 GB), the maxiumum level of parallelism
(make -j) might exahust all available memory and trigger the Linux
OOM killer. Technically, this has nothing to do with Tilck, and it
happens with *any* other big-enough software project, but still it's
better not to suggest everyone to use `make -j` in the documentation
files. Experienced developers are already aware of such things and will
use the right level of parallelism for their machine.
> [docs] Replace `make -j` with `make` in the docs (issue #101)

- .vscode/settings.json
The missing comma on line 201 was preventing changes to the file itself, more specifically when trying to change linter
> [vscode] Fix errors in settings.json

- scripts/cmake-configurator/cmake-configurator.yml
This was problematic because codecov doesn't merge automatically when the CI runs on a subset of the whole project, resulting in wrong coverage reports. Instead it just considers the CI run as if it was a run on the whole project.
Fixing bug introduced in #109.
> [azure] removed coverage from cmake-configurator.yml

- other/toolchain_builds.yml
Opensuse, debian and fedora containers pass. The arch container needs to be regenerated, but this will be done with a dockerfile in another commit.
> [ci-fix] add gmock to toolchain

- CMakeLists.txt
- other/cmake/build_modules.cmake
- other/cmake/wrapped_syms.cmake
- tests/unit/CMakeLists.txt
- tests/unit/mock_experiments.cpp
When the symbol weakening was introduced in Tilck to allow wrapping of symbols in the same translation unit, the TOOL_WS (weaken_syms) was run only against the main `kernel_for_test` static library. Now that the technology proved to be useful in practice with GMock, it's time to patch also the _noarch static libraries generated by modules that are linked to the gtest executable. This will allow unit tests to mock symbols in all the whitelisted "noarch" modules. Currently they are:
- console
- tracing
- sysfs
> [cmake] Patch with TOOL_WS each module linked to gtests

- include/tilck/kernel/test/tracing.h
- modules/tracing/tracing.c
- other/cmake/wrapped_syms.cmake
- tests/unit/mocked_funcs.h
- tests/unit/tracing_test.cpp
Closes #146. Codecov report [here](https://app.codecov.io/gh/michelececcacci/tilck/blob/addtest/modules/tracing/tracing.c/). Reached 100% coverage just with unit tests, but we may need more extensive testing.
> [gtest] add tests for tracing functions (#146)

- tests/unit/tracing_test.cpp
I also noticed that calling the function with both arguments set to NULL generates a segmentation fault, not sure if that's intended.
> [gtests] add more robust testing for simple_wildcard_match

- kernel/arch/x86_64/debug.c
- kernel/arch/x86_64/fault_resumable.S
- kernel/arch/x86_64/paging64.c
This allows the x86-64 Tilck to:
- initialize the textmode_video term
- initialize term
- initialize the console
- run panic() and display a message correctly
> [64-bit] Introduce a fake implementation for fault_resumable_call()

- kernel/arch/x86_64/paging64.c
- kernel/arch/x86_64/start.S
@rviu I didn't do a careful review of your change and now, after working on the project, I found a buffer overflow in start.S. Here's the fix with additional simplifications, FYI.
> Fix start.S for x86-64

- CMakeLists.txt
- config/mod_tracing.h
- include/tilck/mods/tracing.h
- kernel/misc.c
- kernel/printk.c
- modules/debugpanel/dp_tracing.c
- modules/debugpanel/termutil.h
- modules/pci/generic_x86/pci.c
- modules/tracing/tracing.c
- modules/tracing/tracing_metadata.c
This series of patches makes possible `trace_printk()` to be initialized independently from the rest of the `tracing` module and makes `printk()` store the log messages in the `trace_printk()` buffer as well. This was challenging since `printk()` works in many contexts including IRQs handlers (while `trace_printk()` didn't) and also `printk()` have a different semantic compared to `trace_printk()`: `printk()` doesn't force single-line messages and a new line at the end of it is optional. That is also required by the ACPICA log function. On the other side, `trace_printk()` was designed to be used as a pure logger. Now, with quite many tricks, all the `printk()` messages go to the `trace_printk()` buffer, even the early boot messages that are kept initially in the ringbuffer. Many …
> Replicate printk() messages in the trace event buffer

- include/tilck/kernel/term_aux.h
Hi @vvaltchev
I noticed that it is forgot to add the mutex protection before calling `safe_ringbuf_write_elem()` in `term_execute_or_enqueue_action_template()`. 
I discovered this problem when this `panic("Read from safe_ringbuf interrupted on-going write. Not supported")` occurred during a long period of testing runall.
> [term] disable preemption before safe_ringbuf_write_elem()

- kernel/interrupts.c
Hi @vvaltchev 
In` irq_resched()`,  if `do_schedule()` just returned, then `irq_entry()` will return with interrupts enabled! This doesn't seem to cause any problems with the i386 architecture. But for developers trying to port tilck to other architectures, they often assume that the interrupt is off when `irq_entry()` returns. Therefore, disable interrupts here to avoid causing confusion for developers.
> [interrupts] Disable irq if do_schedule() just returned in irq_resched()

- common/3rd_party/fdt_helper.c
- include/3rd_party/fdt_helper.h
- include/tilck/common/arch/riscv/image.h
- include/tilck/kernel/arch/riscv/arch_utils.h
- include/tilck/kernel/arch/riscv/sbi.h
- include/tilck/kernel/hal.h
- kernel/arch/riscv/cpu_features.c
- kernel/arch/riscv/early_fdt.c
- kernel/arch/riscv/paging.c
- kernel/arch/riscv/sbi.c
- kernel/arch/riscv/start.S
Hi @vvaltchev 
riscv init code before entering kmain():
1. setup early mapping;
2. get memory map and simple-fb param from fdt; (Note: The official u-boot does not implement simple-fb on qemu-virt yet, but as far as I know, some riscv chip vendors have released their own u-boot which already has implementations of simple-fb! (e.g. Allwinner D1、Sophgo riscv series))
3. enable virtual address;
4. get cpu features from fdt;
> [riscv64] early init code

- include/tilck/kernel/arch/riscv/asm_defs.h
- kernel/arch/riscv/debug.c
- kernel/arch/riscv/fault.c
- kernel/arch/riscv/fault_resumable.S
- kernel/arch/riscv/panic.c
- kernel/arch/riscv/trap_entry.S
- modules/irqchip/riscv/riscv-plic.c
- modules/serial/riscv/fdt_serial.c
Hi @vvaltchev 
In `fdt_serial.c`, I added some temporary code, mainly to enable early serial output. When the serial driver is updated in the future, these temporary code will be overwritten.
> [riscv64] Implement exception handling and panic

- kernel/arch/riscv/paging.c
- kernel/arch/riscv/paging_generic.c
- kernel/arch/riscv/paging_int.h
Hi @vvaltchev
Implement virtual memory management.
Only the three-level page table(sv-39) has been fully tested. (Note: sv-39 is the most commonly used configuration, almost all risc64 chips support sv-39)
> [riscv64] Implement virtual memory management

- kernel/mm/system_mmap.c
Hi @vvaltchev
`linear_map_mem_region()` previously had an assumption that the memory physical address would start at zero, but that assumption no longer applies.
> [system_mmap] Fix case where memory is not from zero

- include/tilck/mods/irqchip.h
- kernel/arch/riscv/cpu.c
- kernel/arch/riscv/irq.c
- kernel/arch/riscv/mmap.c
- kernel/arch/riscv64/linker_script.ld
- modules/irqchip/riscv/fdt_irqchip.c
- modules/irqchip/riscv/riscv-intc.c
- modules/irqchip/riscv/riscv-plic.c
Hi @vvaltchev 
This framework implements concepts similar to linux interrupt domains. The framework resolves the dependencies of interrupt controllers in the device tree and initializes them in order; Peripherals do not need to worry about the interrupt hardware connection when they request an interrupt, the framework will take care of these problems according to the device tree; And the interrupt number is dynamically assigned.
On a typical embedded chip, the number of interrupt controllers is relatively large, and there may be more than three levels of connection between interrupt controllers (such as “intc->plic->gpio->peripherals” on riscv). Therefore, we must use a more flexible approach to management interrupt, rather than using hard-coded interrupt numbers like x86.
> [riscv64] Introduce a simple irqchip framework

- include/tilck/kernel/arch/i386/asm_defs.h
- include/tilck/kernel/arch/riscv/asm_defs.h
- include/tilck/kernel/sched.h
- include/tilck/kernel/switch.h
- kernel/arch/i386/paging.c
- kernel/arch/i386/process32.c
- kernel/arch/riscv/cpu.c
- kernel/arch/riscv/paging.c
- kernel/arch/riscv/process_riscv.c
- kernel/fork.c
- kernel/interrupts.c
- kernel/process.c
- kernel/sched.c
- kernel/switch.c
Hi @vvaltchev 
As we discussed in #201, here is a proposal for improve the running_in_kernel.
Make `running_in_kernel` a bit-field variable, with the highest bit indicating weather we are in a syscall and low bits for fault count.
> [sched] Improve running_in_kernel

- kernel/arch/riscv/fault_resumable.S
Extracted a0 value which set in `handle_resumable_fault()` when returned from a fault.
This place can cause exceptions very occasionally.
Btw, when these bugs mentioned by these PRs are fixed, riscv64 should at least be able to run runall tests stably for a long time.
> [riscv] fix fault_resumable_call() when returned from fault

- kernel/arch/riscv/paging.c
Now riscv64 NOCOW build should work correctly.
> [riscv] fix NOCOW pdir_deep_clone()

- modules/serial/riscv/fdt_serial.c
- modules/serial/riscv/fdt_serial.h
- modules/serial/riscv/ns16550.c
Introduce '`clr_i`' member in `struct fdt_serial_ops`, to clear/mask the pending interrupt. (Note: for IRQ_TYPE_LEVEL_HIGH type uart irq, the interrupt flag needs to be cleared in the interrupt handler. The qemu-virt platform seems to use uart interrupts of type IRQ_TYPE_EDGE_RISING)
> [riscv][fdt_serial] Minor refactor seiral driver

- kernel/arch/riscv/cpu_features.c
- kernel/arch/riscv/early_fdt.c
- kernel/arch/riscv/paging.c
- kernel/arch/riscv/start.S
`early_get_cpu_features()` must be down even before `init_early_mapping()` (before virtual memory is enabled)
> [riscv] refactor init_early_mapping()

- other/bsp/riscv64/licheerv-nano/board_bsp.cmake
- other/bsp/riscv64/licheerv-nano/bootloader
- other/bsp/riscv64/licheerv-nano/fit-image.its
- other/bsp/riscv64/licheerv-nano/u-boot.cmd
- other/bsp/riscv64/licheerv-nano/uEnv.txt
Hi @vvaltchev,
This PR add support for Sipeed licheerv-nano core board ( _https://wiki.sipeed.com/hardware/en/lichee/RV_Nano/1_intro.html_ )
**BSP usage:**
under tilck project:
1. Make image
```
export ARCH=riscv64
export BOARD=licheerv-nano
./scripts/build_toolchain
make
```
2. Then flash `build/tilck.img` into a microSD card;
3. Insert the microsd card into the card slot on the licheerv-nano board;
4. Connect uart0 on the board (baudrate 115200), and power on the board.
5. Have fun!
boot log:
```
FSBL zIXgg9:g605e5cb6-dirty:2024-08-19T16:32:39+08:00
st_on_reason=d0000
st_off_reason=0
P2S/0x1000/0xc00a200.
SD/0x9200/0x1000/0x1000/0.P2E.
DPS/0xa200/0x2000.
SD/0xa200/0x2000/0x2000/0.DPE.
cv181x DDR init.
ddr_param[0]=0x78075562.
pkg_type=5
D1_3_2
DDR3-2G-QFN
Data rate=1866.
DDR BIST PASS …
```
> [riscv64][bsp] support sipeed licheerv-nano board

- other/bsp/riscv64/licheerv-nano/bootloader
@vvaltchev 
I'm sorry that I missed the PATH problem in the build_toolchain. When building licheerv-nano's bootloader, it cannot include the PATH of the toolchain's bin, because it need to use the host system's python instead of the python under the toolchain's bin.
Now I have retested the whole process starting with 'git clone' and everything is working fine.
> [riscv64][bsp] fix broken build_toolchain due to PATH

- include/tilck/kernel/arch/riscv/asm_defs.h
Hi @vvaltchev 
I noticed that the release build of riscv64 crashed in the latest ci test. I did some debug work as follows.
In `asm_save_regs_and_schedule()`, `save_callee_regs()` will save all callee saved regs and then call `do_schedule`, if no sched happened, `do_schedule` will just return without execute `resume_callee_regs()`. In this case, the value of the `s1` register will change (but according to the C function call convention, the `s1` register must be restored before returning to the caller).
This is why selftest crashed in the case of release build. When `asm_save_regs_and_schedule()` returns to the caller (`save_regs_and_schedule()`), the value of `s1` has changed. But the caller (that is, `save_regs_and_schedule()`) still assumes that `s1` has not changed at all, thus …
> [riscv64] Fix C function call convention errors in asm_defs.h

- README.md
@aenrbes This PR adds some basic information about the RISCV64 support in Tilck in the main README file. A bit more stuff will follow like the instructions to build for the licheerv-nano board, screenshots etc. RISCV64 will have a dedicated wiki page and README will have a link towards that.
> Update README.md with info about RISCV64 support
